In [1]:
## Let's transform the linear equations system into matrix form A.x = b
import numpy as np
A=np.array( [ [3, 0.5,1],[2, 0.1,0],[-1, -1,1]])
print(A)


[[ 3.   0.5  1. ]
 [ 2.   0.1  0. ]
 [-1.  -1.   1. ]]


In [2]:
# Let's calculate rank of matrix A
print( np.linalg.matrix_rank(A) )

3


In [3]:
# Let's calculate the rank of matrix [A|b]
# b is a vector [1 2 1]
A2=np.array( [ [3, 0.5,1,1],[2, 0.1,0,2],[-1, -1,1,1]])
print(A2)

[[ 3.   0.5  1.   1. ]
 [ 2.   0.1  0.   2. ]
 [-1.  -1.   1.   1. ]]


In [4]:
# If the rank of  [A|b] is equal with rank of A, the solution is unique
print( np.linalg.matrix_rank(A2) )

3


In [5]:
## Youpi! the solution is unique : rank[A|b] = rank[A] = 3 . Thanks to Rouché-Capelli

In [6]:
#Let's define vector b
b=np.array([1,2,1])
print(b)

[1 2 1]


In [7]:
# the rank of A is equal with the rank of A2  (aka 3)
# therefore the solution is unique (Rouché-Capelli Theorem)
# Now it is safe to solve the linear equations system

In [8]:
x=np.linalg.solve(A,b)
print(x)
# x is a solution vector (x was a variable, after solving it is a solution)

[ 1.15384615 -3.07692308 -0.92307692]


In [9]:
## checking the solution
## A.x=b

In [10]:
## there are many ways to do matrix multiplication : one of them is to use the @ operator
b2=A@x
print(b2)

[1. 2. 1.]


In [11]:
print(b)

[1 2 1]


In [12]:
## note that b2 matches with b (aka b2==b)